name: Selenoid Tests Workflow
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  
        uses: actions/checkout@v3 
      - name: Create test image
        run: docker build -t test .
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0
      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test